# Generated by Django 6.0.3 on 2026-07-16 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.TextField(db_column='password_hash')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('WORKSHOP_OWNER', 'Workshop owner'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('PENDING', 'Pending')], default='ACTIVE', max_length=7)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['SUPER_ADMIN', 'WORKSHOP_OWNER', 'CUSTOMER'])), name='users_valid_role'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'BLOCKED', 'PENDING'])), name='users_valid_status')],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Registration'), ('RESET_PASSWORD', 'Reset password')], default='LOGIN', max_length=14)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP',
                'db_table': 'user_otps',
                'indexes': [models.Index(fields=['phone', 'purpose'], name='user_otps_phone_purpose_idx')],
            },
        ),
    ]
