# Generated by Django 6.0.3 on 2026-07-15 12:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workshops',
                'ordering': ['-premium', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='workshops.workshop')),
            ],
            options={
                'db_table': 'workshop_locations',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='workshops.workshoplocation')),
            ],
            options={
                'db_table': 'working_hours',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='LocationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('RANGE', 'Range'), ('NEGOTIABLE', 'Negotiable')], default='NEGOTIABLE', max_length=10)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_services', to='catalog.service')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='workshops.workshoplocation')),
            ],
            options={
                'db_table': 'location_services',
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshops.workshoplocation')),
            ],
            options={
                'db_table': 'location_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'location', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='workshops.workshoplocation')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['owner'], name='workshops_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'BLOCKED'])), name='workshops_valid_status'),
        ),
        migrations.AddIndex(
            model_name='workshoplocation',
            index=models.Index(fields=['workshop'], name='locations_workshop_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshoplocation',
            constraint=models.UniqueConstraint(fields=('workshop', 'slug'), name='locations_workshop_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workshoplocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('workshop',), name='locations_one_main_per_workshop'),
        ),
        migrations.AddConstraint(
            model_name='workshoplocation',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='locations_rating_0_5'),
        ),
        migrations.AddConstraint(
            model_name='workshoplocation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE'])), name='locations_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='working_hours_valid_day'),
        ),
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.UniqueConstraint(fields=('location', 'day_of_week'), name='working_hours_location_day_uniq'),
        ),
        migrations.AddIndex(
            model_name='locationservice',
            index=models.Index(fields=['location'], name='loc_services_location_idx'),
        ),
        migrations.AddIndex(
            model_name='locationservice',
            index=models.Index(fields=['service'], name='loc_services_service_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationservice',
            constraint=models.UniqueConstraint(fields=('location', 'service'), name='location_services_location_service_uniq'),
        ),
        migrations.AddConstraint(
            model_name='locationservice',
            constraint=models.CheckConstraint(condition=models.Q(('price_type__in', ['FIXED', 'RANGE', 'NEGOTIABLE'])), name='location_services_valid_price_type'),
        ),
        migrations.AddConstraint(
            model_name='locationservice',
            constraint=models.CheckConstraint(condition=models.Q(('price_from__isnull', True), ('price_from__gte', Decimal('0')), _connector='OR'), name='location_services_price_from_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='locationservice',
            constraint=models.CheckConstraint(condition=models.Q(('price_to__isnull', True), ('price_to__gte', Decimal('0')), _connector='OR'), name='location_services_price_to_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='locationservice',
            constraint=models.CheckConstraint(condition=models.Q(('price_from__isnull', True), ('price_to__isnull', True), ('price_to__gte', models.F('price_from')), _connector='OR'), name='location_services_valid_price_range'),
        ),
        migrations.AddConstraint(
            model_name='locationimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('location',), name='location_images_one_primary'),
        ),
    ]
